server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
#  datasource:
#    druid:
#      driver-class-name: ${relic.datasource.driver-class-name}
#      url: jdbc:mysql://${relic.datasource.host}:${relic.datasource.port}/${relic.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: ${relic.datasource.username}
#      password: ${relic.datasource.password}
  datasource:
    driver-class-name: ${relic.datasource.driver-class-name}
    url: jdbc:mysql://${relic.datasource.host}:${relic.datasource.port}/${relic.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${relic.datasource.username}
    password: ${relic.datasource.password}

  data:
    redis:
      host: ${relic.redis.host}
      port: ${relic.redis.port}
      password: ${relic.redis.password}
      database: ${relic.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.relic.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      relic:
        mapper: debug
        service: info
        controller: info

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    swagger-model-name: 实体类列表

relic:
  jwt:
    admin-secret-key: ZO/5IEc8jY5csLQPhQ2nwkXvEbyIL7v/6AvShE0V5Ic=
    admin-ttl: 72000000000
    admin-token-name: token
    knowledge-secret-key: QjnEXgrR7DaaP2quggUJrQED2hVCKVHUcKaHRdMGHdU=
    knowledge-ttl: 72000000000
    knowledge-token-name: token
    museum-secret-key: kR8vN2mP5xL9wQ3jF7tY1bD6hA0cE4gI
    museum-ttl: 72000000000
    museum-token-name: token
    user-secret-key: QjnEXgrR7DaaP2quggUJrQED2hVCKVHUcKaHRdMGHdU=
    user-ttl: 72000000000
    user-token-name: token
    bucket-name: relic-itcast

#  alioss:
#    endpoint: ${relic.alioss.endpoint}
#    access-key-id: ${relic.alioss.access-key-id}
#    access-key-secret: ${relic.alioss.access-key-secret}
#    bucket-name: ${relic.alioss.bucket-name}

